"""
Anki card templates and formatting for Cantonese vocabulary cards.

This module defines the card templates with English front, Cantonese back,
and audio attachment functionality.
"""

import logging
from typing import Dict, Any
import genanki


logger = logging.getLogger(__name__)


class CantoneseCardTemplate:
    """
    Anki card template for Cantonese vocabulary learning.

    Creates two cards per note:
    - Card 1 (English → Cantonese): Front shows English, back shows Cantonese + audio
    - Card 2 (Cantonese → English): Front shows Cantonese + audio, back shows English

    Two model IDs exist to match the two generations of notes:
    - MODEL_ID_NO_JYUTPING (1607392322): for older notes with 4 fields (no Jyutping)
    - MODEL_ID (1607392321): for newer notes with 5 fields (includes Jyutping)

    New notes generated by this tool use MODEL_ID (5 fields with Jyutping).
    """

    # Model ID for new notes (5 fields: English, Cantonese, Jyutping, Audio, Tags)
    MODEL_ID = 1607392321

    # Model ID for legacy notes (4 fields: English, Cantonese, Audio, Tags)
    MODEL_ID_NO_JYUTPING = 1607392322
    
    # CSS styling for the cards
    CSS = """
.card {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
    padding: 20px;
}

.front {
    font-size: 24px;
    font-weight: bold;
    color: black;
    margin-bottom: 20px;
}

.back {
    font-size: 28px;
    font-weight: bold;
    color: black;
    margin: 20px 0;
}

.jyutping {
    font-size: 18px;
    color: #6c757d;
    font-style: italic;
    margin: 8px 0 16px 0;
}

.audio-section {
    margin: 20px 0;
    padding: 15px;
    background-color: #f8f9fa;
    border-radius: 8px;
    border: 1px solid #dee2e6;
}

.audio-label {
    font-size: 14px;
    color: #6c757d;
    margin-bottom: 10px;
}

.tags {
    display: none;
}

/* Mobile responsiveness */
@media (max-width: 480px) {
    .card {
        font-size: 18px;
        padding: 15px;
    }
    
    .front {
        font-size: 22px;
    }
    
    .back {
        font-size: 24px;
    }
}
"""
    
    # ── Card 1: English → Cantonese ──────────────────────────────────────────

    # Front template (English)
    FRONT_TEMPLATE = """
<div class="card">
    <div class="front">
        {{English}}
    </div>
</div>
"""

    # Back template (Cantonese with Jyutping and audio)
    BACK_TEMPLATE = """
<div class="card">
    <div class="front">
        {{English}}
    </div>

    <hr>

    <div class="back">
        {{Cantonese}}
    </div>

    {{#Jyutping}}
    <div class="jyutping">
        {{Jyutping}}
    </div>
    {{/Jyutping}}

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>
</div>
"""

    # ── Card 2: Cantonese → English ───────────────────────────────────────────

    # Front template (Cantonese with Jyutping and audio as the prompt)
    REVERSE_FRONT_TEMPLATE = """
<div class="card">
    <div class="back">
        {{Cantonese}}
    </div>

    {{#Jyutping}}
    <div class="jyutping">
        {{Jyutping}}
    </div>
    {{/Jyutping}}

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>
</div>
"""

    # Back template (reveals the English meaning)
    REVERSE_BACK_TEMPLATE = """
<div class="card">
    <div class="back">
        {{Cantonese}}
    </div>

    {{#Jyutping}}
    <div class="jyutping">
        {{Jyutping}}
    </div>
    {{/Jyutping}}

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>

    <hr>

    <div class="front">
        {{English}}
    </div>
</div>
"""
    
    @classmethod
    def create_model(cls) -> genanki.Model:
        """
        Create the bidirectional Anki model for newer notes (5 fields, with Jyutping).
        """
        logger.info("Creating bidirectional Cantonese card template model (with Jyutping)")

        model = genanki.Model(
            model_id=cls.MODEL_ID,
            name='Cantonese Vocabulary',
            fields=[
                {'name': 'English'},
                {'name': 'Cantonese'},
                {'name': 'Jyutping'},
                {'name': 'Audio'},
                {'name': 'Tags'},
            ],
            templates=[
                {
                    'name': 'English → Cantonese',
                    'qfmt': cls.FRONT_TEMPLATE,
                    'afmt': cls.BACK_TEMPLATE,
                },
                {
                    'name': 'Cantonese → English',
                    'qfmt': cls.REVERSE_FRONT_TEMPLATE,
                    'afmt': cls.REVERSE_BACK_TEMPLATE,
                },
            ],
            css=cls.CSS,
        )

        logger.info(f"Created bidirectional model with ID {cls.MODEL_ID}")
        return model

    @classmethod
    def create_model_no_jyutping(cls) -> genanki.Model:
        """
        Create the bidirectional Anki model for legacy notes (4 fields, no Jyutping).

        These are notes originally created with model ID 1607392319 that have
        fields: English, Cantonese, Audio, Tags (no Jyutping field).
        """
        # Front/back templates without the Jyutping conditional block
        front = """
<div class="card">
    <div class="front">
        {{English}}
    </div>
</div>
"""
        back = """
<div class="card">
    <div class="front">
        {{English}}
    </div>

    <hr>

    <div class="back">
        {{Cantonese}}
    </div>

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>
</div>
"""
        reverse_front = """
<div class="card">
    <div class="back">
        {{Cantonese}}
    </div>

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>
</div>
"""
        reverse_back = """
<div class="card">
    <div class="back">
        {{Cantonese}}
    </div>

    <div class="audio-section">
        <div class="audio-label">🔊 Pronunciation:</div>
        {{Audio}}
    </div>

    <hr>

    <div class="front">
        {{English}}
    </div>
</div>
"""
        logger.info("Creating bidirectional Cantonese card template model (no Jyutping)")

        model = genanki.Model(
            model_id=cls.MODEL_ID_NO_JYUTPING,
            name='Cantonese Vocabulary (Legacy)',
            fields=[
                {'name': 'English'},
                {'name': 'Cantonese'},
                {'name': 'Audio'},
                {'name': 'Tags'},
            ],
            templates=[
                {
                    'name': 'English → Cantonese',
                    'qfmt': front,
                    'afmt': back,
                },
                {
                    'name': 'Cantonese → English',
                    'qfmt': reverse_front,
                    'afmt': reverse_back,
                },
            ],
            css=cls.CSS,
        )

        logger.info(f"Created legacy bidirectional model with ID {cls.MODEL_ID_NO_JYUTPING}")
        return model


class CardFormatter:
    """
    Formats vocabulary data into Anki card fields.
    """
    
    @staticmethod
    def format_card_fields(english: str, cantonese: str, audio_filename: str, 
                          jyutping: str = "", tags: list = None) -> Dict[str, Any]:
        """
        Format vocabulary data into Anki card fields.
        
        Args:
            english: English term
            cantonese: Cantonese term
            audio_filename: Name of the audio file (just filename, not full path)
            jyutping: Jyutping romanization
            tags: List of tags for the card
            
        Returns:
            Dictionary with formatted card fields
        """
        # Format tags
        if tags is None:
            tags = ['cantonese', 'vocabulary']
        
        tag_string = ' '.join(tags)
        
        # Format audio field for Anki
        audio_field = f'[sound:{audio_filename}]'
        
        fields = {
            'English': english.strip(),
            'Cantonese': cantonese.strip(),
            'Jyutping': jyutping.strip() if jyutping else '',
            'Audio': audio_field,
            'Tags': tag_string,
        }
        
        logger.debug(f"Formatted card: {english} → {cantonese} ({audio_filename})")
        return fields
    
    @staticmethod
    def sanitize_filename(text: str) -> str:
        """
        Sanitize text for use in filenames.
        
        Args:
            text: Text to sanitize
            
        Returns:
            Sanitized filename-safe text
        """
        # Remove or replace problematic characters
        import re
        
        # Replace spaces and special characters
        sanitized = re.sub(r'[^\w\-_.]', '_', text)
        
        # Remove multiple underscores
        sanitized = re.sub(r'_+', '_', sanitized)
        
        # Remove leading/trailing underscores
        sanitized = sanitized.strip('_')
        
        # Ensure it's not empty
        if not sanitized:
            sanitized = 'audio'
        
        return sanitized
    
    @staticmethod
    def generate_audio_filename(english: str, cantonese: str, index: int) -> str:
        """
        Generate a unique audio filename for a vocabulary pair.
        
        Args:
            english: English term
            cantonese: Cantonese term
            index: Index of the term (for uniqueness)
            
        Returns:
            Generated filename
        """
        # Create base name from English term
        base_name = CardFormatter.sanitize_filename(english)
        
        # Add index for uniqueness
        filename = f"{base_name}_{index:03d}.wav"
        
        logger.debug(f"Generated audio filename: {filename}")
        return filename